const GITHUB_GRAPHQL = 'https://api.github.com/graphql';
const PROJECT_ID = 'PVT_kwDOD6r-NM4BP_iI';
const STATUS_FIELD_ID = 'PVTSSF_lADOD6r-NM4BP_iIzg-Pa_4';
const PRIORITY_FIELD_ID = 'PVTSSF_lADOD6r-NM4BP_iIzg-PbDA';
const ITERATION_FIELD_ID = 'PVTIF_lADOD6r-NM4BP_iIzg-PbDk';
const STATUS_OPTIONS: Record<string, string> = { 'in_progress': '47fc9ee4', 'in_review': 'aba860b9', 'done': '98236657', 'ci_passed': '47fc9ee4', 'ci_failed': '47fc9ee4', 'backlog': 'f75ad846', 'ready': 'e18bf179' };
const PRIORITY_OPTIONS: Record<string, string> = { 'Critical': '79628723', 'High': '0a877460', 'Medium': 'da944a9c', 'Low': 'da944a9c' };
const ITERATIONS = [ { id: '381c7c80', startDate: '2026-02-23', duration: 14 }, { id: '54cf5c95', startDate: '2026-03-09', duration: 14 }, { id: 'd2c335bc', startDate: '2026-03-23', duration: 14 }, { id: 'b6a8f1bb', startDate: '2026-04-06', duration: 14 }, { id: '955c1297', startDate: '2026-04-20', duration: 14 } ];
function getCurrentIteration(): string { const today = new Date(); for (const iter of ITERATIONS) { const start = new Date(iter.startDate); const end = new Date(iter.startDate); end.setDate(end.getDate() + iter.duration); if (today >= start && today < end) return iter.id; } return ITERATIONS[0].id; }
async function graphqlRequest(query: string, variables: any, token: string): Promise<any> { const response = await fetch(GITHUB_GRAPHQL, { method: 'POST', headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables }) }); return response.json(); }
async function getIssueNodeId(repo: string, issueNumber: number, token: string): Promise<string | null> { const [owner, name] = repo.split('/'); const query = `query($owner: String!, $name: String!, $number: Int!) { repository(owner: $owner, name: $name) { issue(number: $number) { id } } }`; try { const data: any = await graphqlRequest(query, { owner, name, number: issueNumber }, token); return data?.data?.repository?.issue?.id || null; } catch (err) { return null; } }
async function addIssueToProject(issueNodeId: string, token: string): Promise<string | null> { const mutation = `mutation($projectId: ID!, $contentId: ID!) { addProjectV2ItemById(input: { projectId: $projectId contentId: $contentId }) { item { id } } }`; try { const data: any = await graphqlRequest(mutation, { projectId: PROJECT_ID, contentId: issueNodeId }, token); return data?.data?.addProjectV2ItemById?.item?.id || null; } catch (err) { return null; } }
async function updateField(itemId: string, fieldId: string, value: any, token: string): Promise<void> { const mutation = `mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) { updateProjectV2ItemFieldValue(input: { projectId: $projectId itemId: $itemId fieldId: $fieldId value: $value }) { projectV2Item { id } } }`; try { await graphqlRequest(mutation, { projectId: PROJECT_ID, itemId, fieldId, value }, token); } catch (err) { console.error(`[GitHubProjects] Failed to update field:`, err); } }
async function findProjectItem(issueNumber: number, token: string): Promise<string | null> { const query = `query($projectId: ID!) { node(id: $projectId) { ... on ProjectV2 { items(first: 100) { nodes { id content { ... on Issue { number } } } } } } }`; try { const data: any = await graphqlRequest(query, { projectId: PROJECT_ID }, token); const items = data?.data?.node?.items?.nodes || []; const found = items.find((item: any) => item?.content?.number === issueNumber); return found?.id || null; } catch (err) { return null; } }
export async function syncIssueToProject(repo: string, issueNumber: number, status: string, priority: string, token: string): Promise<void> { console.log(`[GitHubProjects] Syncing issue #${issueNumber} status: ${status}`); const issueNodeId = await getIssueNodeId(repo, issueNumber, token); if (!issueNodeId) return; let itemId = await findProjectItem(issueNumber, token); if (!itemId) { itemId = await addIssueToProject(issueNodeId, token); if (!itemId) return; console.log(`Added issue #${issueNumber} to board`); } const statusOptionId = STATUS_OPTIONS[status] || STATUS_OPTIONS['in_progress']; await updateField(itemId, STATUS_FIELD_ID, { singleSelectOptionId: statusOptionId }, token); console.log(`Status updated to: ${status}`); const priorityOptionId = PRIORITY_OPTIONS[priority] || PRIORITY_OPTIONS['Medium']; await updateField(itemId, PRIORITY_FIELD_ID, { singleSelectOptionId: priorityOptionId }, token); console.log(`Priority updated to: ${priority}`); const currentIterationId = getCurrentIteration(); await updateField(itemId, ITERATION_FIELD_ID, { iterationId: currentIterationId }, token); console.log(`Assigned to current iteration: ${currentIterationId}`); }
